### ISSUE TITLE
Only show landlords with issues

### ISSUE THREAD

**Issue by jlbooker** [AppStateESS/slc#7]
On the landlord-tenant report, only show landlords that have an issue. If the landlord hasn't had any issues, then leave them off the list.

**Comment by jlbooker** [comment]
@cambelem This was fixed in the last round of updates, right? Checking to see if I can close this.

**Comment by cambelem** [comment]
Yes, it was added with the modernization branch. I just checked it and it's implemented and working.

**Comment by jlbooker** [comment]
:+1:
