### ISSUE TITLE
Revise Appointment Statistics Report

### ISSUE THREAD

**Issue by jlbooker** [AppStateESS/slc#8]
We need to take a close look at the Appointment Statistics report to make sure that the labels we're using are actually the things we're counting:

* "Total clients" should be the total number of unique client ids with visits during the requested date range.
* Total visits should be the raw number of visit IDs during the requested date range.
* Total first time visits should be the number of non-follow-up visits (during the requested date range)
* New clients should be the number of unique client IDs no seen prior to the requested date range.

**Comment by jlbooker** [comment]
@cambelem Double checking on this one too. Can you double check that all of this is fixed?

**Comment by cambelem** [comment]
Everything looks good, though the Issue per Visit is taking an average so it's odd sometimes. Should I revise the label to say Average Issue per Visit?

**Comment by jlbooker** [comment]
:+1:
